CREATE USER resource_user WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD 'resource_password';
CREATE USER keycloak_user WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD 'keycloak_password';

CREATE DATABASE resource_db OWNER resource_user;
GRANT ALL PRIVILEGES ON DATABASE resource_db TO resource_user;

CREATE DATABASE keycloak_db OWNER keycloak_user;
GRANT ALL PRIVILEGES ON DATABASE keycloak_db TO keycloak_user;
